// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mksccujthnioivzhlwse.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1rc2NjdWp0aG5pb2l2emhsd3NlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1ODg5ODMsImV4cCI6MjA3MTE2NDk4M30.aMFvXIY_l_l8OLsYtr_z3ixmg-Wi803SCh8x-iiRekU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});